name: Build PDF

on:
  push:
    branches: [ master ]
  #https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_dispatch
  workflow_dispatch:

jobs:
  check-spelling:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
        
      - name: Vale
        uses: errata-ai/vale-action@v1.4.0
        with:
          # Optional
          styles: |
            https://github.com/errata-ai/Microsoft/releases/latest/download/Microsoft.zip
            https://github.com/errata-ai/write-good/releases/latest/download/write-good.zip
          config: https://raw.githubusercontent.com/errata-ai/vale/master/.vale.ini
          files: '["Rose_CV.tex"]'
        env:
          # Required
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          
  build_latex:
    needs: check-spelling
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: Rose_CV.tex
          args: "-xelatex -file-line-error -interaction=nonstopmode"
          
      - name: Publish PDF
        run: |
          # if [ git branch | grep \* | cut -d ' ' -f2 | egrep 'master' ]; then
          git checkout --orphan master-pdf
          git rm -rf .
          git add -f Rose_CV.pdf
          git -c user.name='github_actions' -c user.email='github_actions' commit -m "current pdf"
          git push -q -f https://benjamin:${{ secrets.GITHUB_TOKEN }}@github.com/benjaminrose/CV master-pdf
          # fi
